// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnionArcExample.Persistence.Context;

#nullable disable

namespace OnionArcExample.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnionArcExample.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d7143a6-d198-4f25-aef8-277f32ef9d3f"),
                            Description = "Pamuklu ",
                            Name = "Gömlek",
                            Price = 12,
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("3fd523c4-6f75-447e-b6bb-f2a53ddfdfde"),
                            Description = "Kadife ",
                            Name = "Pantolan",
                            Price = 12,
                            Stock = 22
                        },
                        new
                        {
                            Id = new Guid("abdddcd9-06c4-48a8-af20-17b0030fcea4"),
                            Description = "Yün ",
                            Name = "Hırka",
                            Price = 12,
                            Stock = 32
                        },
                        new
                        {
                            Id = new Guid("32425b98-8268-4a05-8478-28412190e231"),
                            Description = "Polyester ",
                            Name = "Kazak",
                            Price = 12,
                            Stock = 42
                        },
                        new
                        {
                            Id = new Guid("e6e9a4bd-a160-4c9a-803f-51420a866be7"),
                            Description = "Keten ",
                            Name = "Etek",
                            Price = 12,
                            Stock = 52
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
